### PR TITLE
2.0 adaption

### PR DESCRIPTION
**Pull request by niklasha**
This is an adaption to RC1, basically just an introduction of the new LoadConnection trait.

### CODE REVIEW

**Comment by shssoichiro** [comment]
Would you mind running rustfmt and then push up again? Thanks!

**Comment by niklasha** [comment]
> Would you mind running rustfmt and then push up again? Thanks!

done

**Comment by niklasha** [comment]
ping

**Comment by shssoichiro** [comment]
Thanks. Sorry I've been so slow with getting this merged. Assuming CI passes, I'll get it merged and publish a new crate version today.

**Pull request merged**
